export const text = {
  en: {
    connecting: "Preparing MoPlayer Pro",
    activateTitle: "Activate this Windows PC",
    activateBody: "Scan the QR code or enter the code on moalfarras.space to link this computer and receive your source securely.",
    createQr: "Create QR code",
    refreshQr: "Refresh QR",
    copyCode: "Copy code",
    waitingActivation: "Waiting for activation on the website…",
    openWebsite: "Open website",
    loginTitle: "Connect your source",
    loginBody: "Add your own legal M3U/M3U8 playlist or Xtream credentials. No channels are included.",
    legalPlayerOnly: "Legal player only",
    xtream: "Xtream",
    m3u: "M3U URL",
    save: "Connect",
    sync: "Refresh",
    home: "Home",
    live: "Live TV",
    movies: "Movies",
    series: "Series",
    episodes: "Episodes",
    search: "Search",
    favorites: "Favorites",
    settings: "Settings",
    license: "License",
    support: "Support",
    noContent: "No library yet. Add a playlist or activate with QR to load your own source.",
    legal: "MoPlayer Pro does not provide, host, sell, or distribute any media content. Users must add their own legally obtained playlists or Xtream credentials.",
    failedStream: "Failed to load stream",
    retry: "Retry",
    copyDevice: "Copy Device ID",
    copied: "Copied",
    checkUpdates: "Check for updates",
    contactSupport: "Contact support",
    exportLogs: "Export logs",
    fullscreen: "Fullscreen",
    sourceExpired: "Source expired or unavailable. Refresh the QR activation.",
    networkError: "Network error. Check the source and try again.",
    unsupported: "Unsupported format in the internal player.",
    weather: "Weather",
    matches: "Matches",
    activate: "Activate",
    source: "Source",
    player: "Player",
    qaMode: "QA fixture mode",
    connectingSource: "Checking your account with the provider...",
    loginSuccess: "Account verified. Loading your library...",
    loadingXtream: "Loading Xtream library",
    loadingM3u: "Loading M3U playlist",
    loadingEpisodes: "Loading episodes",
    openM3uFile: "Open M3U file",
    addSource: "Add source",
    backToApp: "Back",
    sources: "Sources",
    activeSource: "Active source",
    useSource: "Use",
    removeSource: "Remove",
    noSources: "No saved sources yet.",
    accountStatus: "Account status",
    accountExpiry: "Expires",
    accountConnections: "Connections",
    accountTrial: "Trial account",
    accountCreated: "Created",
    never: "Unlimited",
    continueWatching: "Continue watching",
    recentlyAdded: "Recently added",
    allCategories: "All",
    itemsLabel: "items",
    noResults: "No matching items.",
    typeToSearch: "Search channels, movies, series...",
    all: "All",
    upToDate: "You are on the latest version.",
    updateAvailable: "A newer version is available on the website.",
    updateCheckFailed: "Could not check for updates.",
    downloadUpdate: "Download update",
    updateLater: "Later",
    updateDownloading: "Downloading update",
    updateReady: "Update ready",
    updateRestart: "Restart to update",
    matchesTitle: "Football matches",
    liveNow: "Live",
    finishedLabel: "Finished",
    upcomingLabel: "Upcoming",
    matchesEmpty: "No matches right now. Check back later.",
    allMatches: "All matches",
    showMore: "Show more",
    nowPlaying: "Now playing",
    liveBadge: "LIVE",
    buffering: "Buffering",
    audioTrack: "Audio",
    relatedTitle: "Up next",
    appearance: "Appearance",
    playbackCache: "Playback and library",
    widgetsControls: "Widgets and services",
    about: "About",
    arabicInterface: "Arabic interface",
    compactDensityLabel: "Compact density",
    fullscreenOnLaunchLabel: "Fullscreen on launch",
    autoPlayLastLiveLabel: "Resume last live channel on launch",
    hideEmptyCategoriesLabel: "Hide empty categories",
    coverVideoLabel: "Cover video frame",
    showWeatherLabel: "Show weather",
    showMatchesLabel: "Show matches",
    weatherCityLabel: "Weather city",
    parentalLabel: "Parental control filter",
    appVersion: "App version",
    deviceId: "Device ID",
    localEncryption: "Local encryption",
    encryptionOk: "Available",
    encryptionFallback: "Fallback storage",
    deviceLabel: "Device",
    platformLabel: "Platform",
    statusLabel: "Status",
    statusRegistered: "Registered locally. Activation appears in Admin after QR confirmation.",
    openActivation: "Open activation",
    userData: "User data",
    deleteConfirm: "Remove this source and its saved credentials?",
    sourceSwitched: "Source switched. Refresh to load its library.",
    minutes: "min",
    welcomeBack: "Discover limitless entertainment",
    quickSync: "Update",
    quickLoad: "Load",
    website: "Website",
    windowsPc: "Windows PC",
    noSource: "No source",
    sourceSubscription: "Source subscription",
    host: "Host",
    localSource: "Local source",
    liveFormat: "Live format",
    timezone: "Timezone",
    unknown: "Unknown",
    auto: "Auto",
    profileName: "Profile name",
    profilePlaceholder: "Living room",
    playlistPlaceholder: "My playlist",
    serverUrl: "Server URL",
    username: "Username",
    password: "Password",
    m3uUrlLabel: "M3U / M3U8 URL",
    epgUrl: "EPG URL",
    epgPlaceholder: "Optional XMLTV URL",
    sourceRequired: "Server, username, and password are required.",
    m3uRequired: "M3U URL is required.",
    libraryReady: "Library ready",
    xtreamLoaded: "Xtream source loaded.",
    m3uXtreamLoaded: "M3U Plus source loaded through Xtream API.",
    m3uSaved: "M3U source saved locally.",
    qrXtreamImported: "QR Xtream source imported.",
    qrSaved: "QR source saved locally.",
    activationCreated: "Activation code created.",
    activationFailed: "Could not create activation code.",
    waitingForSource: "Waiting for source details",
    activationCheckFailed: "Activation check failed",
    itemNotPlayable: "This item has no playable stream URL.",
    episodesLoadFailed: "Could not load episodes.",
    episodesLoaded: "episodes loaded",
    noEpisodesLoaded: "No episodes loaded for this series yet.",
    licenseStatus: "License status",
    providerExpiry: "Provider expiry",
    supportDeviceInfo: "Support / Device Info",
    logsExported: "Logs exported",
    currentWeather: "Current weather",
    weatherUnavailable: "Weather service is not available right now.",
    weatherApiNote: "Uses the website weather API.",
    humidity: "Humidity",
    wind: "Wind",
    scheduled: "Scheduled",
    noMatch: "No match",
    footballUnavailable: "Football service is empty or unavailable.",
    liveService: "Live service",
    seasonLabel: "Season",
    genreLabel: "Genre",
    directorLabel: "Director",
    castLabel: "Cast",
    multiView: "Multi-view",
    nowLabel: "Now",
    nextLabel: "Next",
    guideLabel: "TV Guide",
    subtitlesLabel: "Subtitles",
    offLabel: "Off",
    pickChannel: "Pick a channel",
    addTile: "Add channel",
    removeTile: "Remove",
    expandTile: "Open in player",
    audioOn: "Audio",
    connectionLimitWarning: "Provider limit: {count} simultaneous connection(s). Extra screens may buffer.",
    parentalPinTitle: "Parental PIN",
    setPinBody: "Set a 4-digit PIN to lock the parental filter.",
    enterPinBody: "Enter the PIN to turn off the parental filter.",
    wrongPin: "Wrong PIN. Try again.",
    confirm: "Confirm",
    cancel: "Cancel",
    goToChannel: "Go to channel",
    qualityLabel: "Quality",
    channelsLabel: "Channels",
    shortcutsTitle: "Keyboard shortcuts",
    defaultSpeedLabel: "Default playback speed",
    clearCache: "Clear library cache",
    cacheCleared: "Library cache cleared. Refresh to reload.",
    openDataFolder: "Open data folder",
    catchupLabel: "Catch-up",
    recordLabel: "Record",
    recordingLabel: "Recording...",
    sleepTimer: "Sleep timer",
    pipLabel: "Mini player (PiP)",
    aspectLabel: "Aspect ratio",
    alwaysOnTop: "Always on top",
    trailerLabel: "Trailer",
    hideCategory: "Hide this category",
    hiddenCategoriesTitle: "Hidden categories",
    restoreLabel: "Restore",
    themeLabel: "Accent color",
  },
  ar: {
    connecting: "تجهيز MoPlayer Pro",
    activateTitle: "تفعيل هذا الكمبيوتر",
    activateBody: "امسح رمز QR أو أدخل الكود على moalfarras.space لربط هذا الكمبيوتر واستلام مصدرك بأمان.",
    createQr: "إنشاء رمز QR",
    refreshQr: "تحديث QR",
    copyCode: "نسخ الكود",
    waitingActivation: "بانتظار التفعيل على الموقع…",
    openWebsite: "فتح الموقع",
    loginTitle: "اربط مصدرك",
    loginBody: "أضف قائمة M3U/M3U8 أو بيانات Xtream القانونية الخاصة بك. التطبيق لا يحتوي على أي قنوات مدمجة.",
    legalPlayerOnly: "مشغل قانوني فقط",
    xtream: "Xtream",
    m3u: "رابط M3U",
    save: "اتصال",
    sync: "تحديث",
    home: "الرئيسية",
    live: "البث المباشر",
    movies: "الأفلام",
    series: "المسلسلات",
    episodes: "الحلقات",
    search: "البحث",
    favorites: "المفضلة",
    settings: "الإعدادات",
    license: "الترخيص",
    support: "الدعم",
    noContent: "لا توجد مكتبة بعد. أضف قائمة تشغيل أو فعّل QR لتحميل مصدرك الخاص.",
    legal: "MoPlayer Pro لا يوفر أو يستضيف أو يبيع أو يوزع أي محتوى إعلامي. يجب على المستخدم إضافة قوائمه أو بيانات Xtream القانونية الخاصة به.",
    failedStream: "تعذر تشغيل البث",
    retry: "إعادة المحاولة",
    copyDevice: "نسخ رقم الجهاز",
    copied: "تم النسخ",
    checkUpdates: "فحص التحديثات",
    contactSupport: "الدعم",
    exportLogs: "تصدير السجلات",
    fullscreen: "ملء الشاشة",
    sourceExpired: "انتهى المصدر أو لم يعد متاحاً. حدّث تفعيل QR.",
    networkError: "خطأ في الشبكة. تحقق من المصدر وحاول مرة أخرى.",
    unsupported: "صيغة غير مدعومة داخل المشغل الداخلي.",
    weather: "الطقس",
    matches: "المباريات",
    activate: "تفعيل",
    source: "المصدر",
    player: "المشغل",
    qaMode: "وضع فحص QA",
    connectingSource: "جار التحقق من الحساب لدى المزوّد...",
    loginSuccess: "تم التحقق من الحساب. جار تحميل المكتبة...",
    loadingXtream: "جار تحميل مكتبة Xtream",
    loadingM3u: "جار تحميل قائمة M3U",
    loadingEpisodes: "جار تحميل الحلقات",
    openM3uFile: "فتح ملف M3U",
    addSource: "إضافة مصدر",
    backToApp: "رجوع",
    sources: "المصادر",
    activeSource: "المصدر النشط",
    useSource: "استخدام",
    removeSource: "حذف",
    noSources: "لا توجد مصادر محفوظة بعد.",
    accountStatus: "حالة الحساب",
    accountExpiry: "ينتهي في",
    accountConnections: "الاتصالات",
    accountTrial: "حساب تجريبي",
    accountCreated: "تاريخ الإنشاء",
    never: "غير محدود",
    continueWatching: "متابعة المشاهدة",
    recentlyAdded: "أضيف حديثاً",
    allCategories: "الكل",
    itemsLabel: "عنصر",
    noResults: "لا توجد نتائج مطابقة.",
    typeToSearch: "ابحث عن قنوات أو أفلام أو مسلسلات...",
    all: "الكل",
    upToDate: "أنت على أحدث إصدار.",
    updateAvailable: "يوجد إصدار أحدث على الموقع.",
    updateCheckFailed: "تعذر فحص التحديثات.",
    downloadUpdate: "تنزيل التحديث",
    updateLater: "لاحقًا",
    updateDownloading: "جارٍ تنزيل التحديث",
    updateReady: "التحديث جاهز",
    updateRestart: "أعد التشغيل للتحديث",
    matchesTitle: "مباريات كرة القدم",
    liveNow: "مباشر",
    finishedLabel: "انتهت",
    upcomingLabel: "قادمة",
    matchesEmpty: "لا توجد مباريات حالياً. عُد لاحقاً.",
    allMatches: "كل المباريات",
    showMore: "عرض المزيد",
    nowPlaying: "يعرض الآن",
    liveBadge: "مباشر",
    buffering: "تحميل مؤقت",
    audioTrack: "الصوت",
    relatedTitle: "التالي",
    appearance: "المظهر",
    playbackCache: "التشغيل والمكتبة",
    widgetsControls: "الودجات والخدمات",
    about: "حول التطبيق",
    arabicInterface: "الواجهة العربية",
    compactDensityLabel: "كثافة مدمجة",
    fullscreenOnLaunchLabel: "ملء الشاشة عند التشغيل",
    autoPlayLastLiveLabel: "استئناف آخر قناة مباشرة عند التشغيل",
    hideEmptyCategoriesLabel: "إخفاء التصنيفات الفارغة",
    coverVideoLabel: "تكبير الفيديو لملء الإطار",
    showWeatherLabel: "عرض الطقس",
    showMatchesLabel: "عرض المباريات",
    weatherCityLabel: "مدينة الطقس",
    parentalLabel: "فلتر الرقابة الأبوية",
    appVersion: "إصدار التطبيق",
    deviceId: "رقم الجهاز",
    localEncryption: "التشفير المحلي",
    encryptionOk: "متاح",
    encryptionFallback: "تخزين بديل",
    deviceLabel: "الجهاز",
    platformLabel: "المنصة",
    statusLabel: "الحالة",
    statusRegistered: "مسجل محلياً. يظهر التفعيل في لوحة الإدارة بعد تأكيد QR.",
    openActivation: "فتح صفحة التفعيل",
    userData: "بيانات المستخدم",
    deleteConfirm: "حذف هذا المصدر وبياناته المحفوظة؟",
    sourceSwitched: "تم تبديل المصدر. اضغط تحديث لتحميل مكتبته.",
    minutes: "دقيقة",
    welcomeBack: "اكتشف عالمك الترفيهي بلا حدود",
    quickSync: "تحديث",
    quickLoad: "تحميل",
    website: "الموقع",
    windowsPc: "كمبيوتر ويندوز",
    noSource: "لا يوجد مصدر",
    sourceSubscription: "اشتراك المصدر",
    host: "المضيف",
    localSource: "مصدر محلي",
    liveFormat: "صيغة البث المباشر",
    timezone: "المنطقة الزمنية",
    unknown: "غير معروف",
    auto: "تلقائي",
    profileName: "اسم الملف",
    profilePlaceholder: "غرفة المعيشة",
    playlistPlaceholder: "قائمتي",
    serverUrl: "رابط السيرفر",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    m3uUrlLabel: "رابط M3U / M3U8",
    epgUrl: "رابط EPG",
    epgPlaceholder: "رابط XMLTV اختياري",
    sourceRequired: "رابط السيرفر واسم المستخدم وكلمة المرور مطلوبة.",
    m3uRequired: "رابط M3U مطلوب.",
    libraryReady: "المكتبة جاهزة",
    xtreamLoaded: "تم تحميل مصدر Xtream.",
    m3uXtreamLoaded: "تم تحميل مصدر M3U Plus عبر Xtream API.",
    m3uSaved: "تم حفظ مصدر M3U محلياً.",
    qrXtreamImported: "تم استيراد مصدر Xtream عبر QR.",
    qrSaved: "تم حفظ مصدر QR محلياً.",
    activationCreated: "تم إنشاء كود التفعيل.",
    activationFailed: "تعذر إنشاء كود التفعيل.",
    waitingForSource: "بانتظار بيانات المصدر",
    activationCheckFailed: "فشل فحص التفعيل",
    itemNotPlayable: "هذا العنصر لا يحتوي على رابط تشغيل.",
    episodesLoadFailed: "تعذر تحميل الحلقات.",
    episodesLoaded: "حلقة محملة",
    noEpisodesLoaded: "لا توجد حلقات محملة لهذا المسلسل بعد.",
    licenseStatus: "حالة الترخيص",
    providerExpiry: "انتهاء اشتراك المزوّد",
    supportDeviceInfo: "الدعم ومعلومات الجهاز",
    logsExported: "تم تصدير السجلات",
    currentWeather: "الطقس الحالي",
    weatherUnavailable: "خدمة الطقس غير متاحة الآن.",
    weatherApiNote: "تستخدم واجهة الطقس في الموقع.",
    humidity: "الرطوبة",
    wind: "الرياح",
    scheduled: "مجدولة",
    noMatch: "لا توجد مباراة",
    footballUnavailable: "خدمة المباريات فارغة أو غير متاحة.",
    liveService: "خدمة مباشرة",
    seasonLabel: "الموسم",
    genreLabel: "النوع",
    directorLabel: "المخرج",
    castLabel: "البطولة",
    multiView: "شاشات متعددة",
    nowLabel: "الآن",
    nextLabel: "التالي",
    guideLabel: "دليل البرامج",
    subtitlesLabel: "الترجمة",
    offLabel: "إيقاف",
    pickChannel: "اختر قناة",
    addTile: "إضافة قناة",
    removeTile: "إزالة",
    expandTile: "فتح في المشغل",
    audioOn: "الصوت",
    connectionLimitWarning: "حد المزود: {count} اتصال متزامن. قد تتوقف الشاشات الإضافية أو تحتاج وقتًا أطول.",
    parentalPinTitle: "الرقم السري للرقابة",
    setPinBody: "عيّن رقماً سرياً من 4 أرقام لقفل فلتر الرقابة الأبوية.",
    enterPinBody: "أدخل الرقم السري لإيقاف فلتر الرقابة الأبوية.",
    wrongPin: "رقم سري خاطئ. حاول مرة أخرى.",
    confirm: "تأكيد",
    cancel: "إلغاء",
    goToChannel: "الانتقال للقناة",
    qualityLabel: "الجودة",
    channelsLabel: "القنوات",
    shortcutsTitle: "اختصارات الكيبورد",
    defaultSpeedLabel: "سرعة التشغيل الافتراضية",
    clearCache: "مسح ذاكرة المكتبة",
    cacheCleared: "تم مسح ذاكرة المكتبة. اضغط تحديث لإعادة التحميل.",
    openDataFolder: "فتح مجلد البيانات",
    catchupLabel: "مشاهدة راجعة",
    recordLabel: "تسجيل",
    recordingLabel: "جارٍ التسجيل...",
    sleepTimer: "مؤقت النوم",
    pipLabel: "مشغل مصغر (PiP)",
    aspectLabel: "أبعاد الصورة",
    alwaysOnTop: "دائماً في الأعلى",
    trailerLabel: "الإعلان",
    hideCategory: "إخفاء هذه المجموعة",
    hiddenCategoriesTitle: "مجموعات مخفية",
    restoreLabel: "استعادة",
    themeLabel: "لون الواجهة",
  },
} as const;

export type Labels = Record<keyof typeof text.en, string>;

export function labelsFor(language: "en" | "ar"): Labels {
  return text[language] as unknown as Labels;
}
