import type { Locale } from "@/types/cms";

type SeoPage = {
  title: string;
  description: string;
  image: string;
  keywords?: string[];
};

export const seoData = {
  en: {
    home: {
      title: "Professional Website Design, Web Apps & Digital Products",
      description: "Mohammad Alfarras — Syrian web designer & developer in Germany. Professional website design, fast Arabic/English landing pages and online stores, MoPlayer apps, and clear Arabic tech content.",
      image: "/images/protofeilnew.jpeg",
      keywords: [
        "Mohammad Alfarras",
        "website design",
        "professional website design",
        "web designer",
        "web developer Germany",
        "Arabic website design",
        "website developer",
        "product interface designer",
        "bilingual websites",
        "Arabic RTL websites",
        "landing page design",
        "online store design",
        "MoPlayer",
        "IPTV player app",
        "Android TV apps",
        "product UI design",
        "landing pages",
        "digital products",
        "freelance web developer",
      ],
    },
    about: {
      title: "About",
      description: "Meet Mohammad Alfarras, a Germany-based builder working across web interfaces, digital products, logistics, and Arabic tech content.",
      image: "/images/protofeilnew.jpeg",
      keywords: [
        "Mohammad Alfarras",
        "about Mohammad Alfarras",
        "web developer",
        "product builder",
        "Germany",
        "Syria",
        "logistics",
        "Arabic tech content creator",
      ],
    },
    services: {
      title: "Website Design & Web Development Services",
      description: "Professional website design services: business websites, landing pages that sell, online stores and web apps — bilingual Arabic/English, fast on mobile, SEO-ready.",
      image: "/images/service_web.png",
      keywords: [
        "web design",
        "web development",
        "website development",
        "product interfaces",
        "Arabic websites",
        "bilingual websites",
        "landing pages",
        "UI/UX design",
        "product pages",
        "SEO",
        "web performance",
        "web apps",
        "hire web developer",
      ],
    },
    cv: {
      title: "CV",
      description: "Professional experience across logistics operations, web engineering, product delivery, and bilingual communication.",
      image: "/images/portrait.jpg",
      keywords: [
        "Mohammad Alfarras CV",
        "resume",
        "web engineer",
        "frontend developer",
        "logistics operations",
        "product delivery",
        "bilingual professional",
      ],
    },
    work: {
      title: "Work & Case Studies",
      description: "Selected websites and product case studies shaped around clarity, trust, mobile usability, and direct conversion paths.",
      image: "/images/projects/adtransporte-home.png",
      keywords: [
        "portfolio",
        "case studies",
        "web design portfolio",
        "projects",
        "websites",
        "business websites",
        "Schnell Sicher Umzug",
        "AD Fahrzeugtransporte",
        "MoPlayer",
        "conversion-focused design",
      ],
    },
    youtube: {
      title: "YouTube",
      description: "Arabic technology reviews, practical tutorials, Android TV experiments, and product stories with real publication dates.",
      image: "/images/yt-channel-hero.png",
      keywords: [
        "Arabic tech YouTube",
        "technology reviews",
        "tutorials",
        "Android TV",
        "MoPlayer",
        "tech channel",
        "Mohammad Alfarras YouTube",
      ],
    },
    contact: {
      title: "Contact",
      description: "Start a website, product page, redesign, MoPlayer support, or digital presentation project with Mohammad Alfarras.",
      image: "/images/service_tech.png",
      keywords: [
        "contact Mohammad Alfarras",
        "hire web developer",
        "start a project",
        "website quote",
        "web design inquiry",
        "MoPlayer support",
      ],
    },
    privacy: {
      title: "Privacy",
      description: "How moalfarras.space handles contact requests, support messages, product data, downloads, and related services.",
      image: "/images/logo.png",
      keywords: ["privacy policy", "data handling", "moalfarras.space", "data protection"],
    },
    apps: {
      title: "Apps & Products",
      description: "Explore MoPlayer Classic, MoPlayer Pro, PC releases, activation, official downloads, support, and product updates.",
      image: "/images/moplayer-pro-hero.webp",
      keywords: [
        "MoPlayer",
        "MoPlayer Classic",
        "MoPlayer Pro",
        "MoPlayer PC",
        "IPTV player",
        "Xtream player",
        "M3U player",
        "Android TV player",
        "Fire TV player",
        "Windows media player",
        "app activation",
        "official downloads",
        "media player apps",
      ],
    },
  },
  ar: {
    home: {
      title: "تصميم مواقع احترافية وتطبيقات ويب — محمد الفراس",
      description: "محمد الفراس — مصمم ومطور مواقع سوري مقيم في ألمانيا. تصميم مواقع احترافية حديثة، صفحات هبوط ومتاجر إلكترونية سريعة بالعربية والإنجليزية، مع تطبيقات MoPlayer ومحتوى تقني عربي واضح.",
      image: "/images/protofeilnew.jpeg",
      keywords: [
        "محمد الفراس",
        "تصميم مواقع",
        "تصميم مواقع احترافية",
        "مصمم مواقع",
        "تصميم موقع الكتروني",
        "انشاء موقع الكتروني",
        "برمجة مواقع",
        "مطور ويب",
        "مطور مواقع",
        "مصمم مواقع سوري",
        "تصميم مواقع سوريا",
        "تصميم مواقع ألمانيا",
        "تصميم متجر الكتروني",
        "صفحات هبوط",
        "مواقع عربية",
        "مواقع ثنائية اللغة",
        "MoPlayer",
        "تطبيق IPTV",
        "تطبيقات Android TV",
        "تصميم واجهات",
        "منتجات رقمية",
        "مطور ويب مستقل",
      ],
    },
    about: {
      title: "عن محمد الفراس",
      description: "تعرّف على محمد الفراس وخبرته في واجهات الويب والمنتجات الرقمية واللوجستيات وصناعة المحتوى التقني العربي.",
      image: "/images/protofeilnew.jpeg",
      keywords: [
        "محمد الفراس",
        "من هو محمد الفراس",
        "مطور ويب",
        "صانع منتجات رقمية",
        "ألمانيا",
        "سوريا",
        "لوجستيات",
        "محتوى تقني عربي",
      ],
    },
    services: {
      title: "خدمات تصميم مواقع وتطوير ويب احترافية",
      description: "خدمات تصميم مواقع احترافية: موقع تعريفي لشركتك، صفحة هبوط تبيع، متجر إلكتروني أو تطبيق ويب — تصميم عربي/إنجليزي سريع على الجوال مع تحسين محركات البحث.",
      image: "/images/service_web.png",
      keywords: [
        "خدمات تصميم مواقع",
        "تصميم مواقع",
        "تصميم مواقع احترافية",
        "تصميم موقع شركة",
        "تصميم صفحة هبوط",
        "تصميم متجر الكتروني",
        "تطوير مواقع",
        "تطوير تطبيقات ويب",
        "أسعار تصميم المواقع",
        "مصمم مواقع عربي",
        "واجهات منتجات",
        "مواقع عربية",
        "مواقع ثنائية اللغة",
        "صفحات هبوط",
        "تصميم واجهات UI/UX",
        "تحسين محركات البحث SEO",
        "أداء المواقع",
        "توظيف مطور ويب",
      ],
    },
    cv: {
      title: "السيرة الذاتية",
      description: "خبرة مهنية تجمع العمليات اللوجستية وهندسة الويب وتسليم المنتجات والتواصل بالعربية والألمانية والإنجليزية.",
      image: "/images/portrait.jpg",
      keywords: [
        "سيرة محمد الفراس الذاتية",
        "السيرة الذاتية",
        "مهندس ويب",
        "مطور واجهات",
        "عمليات لوجستية",
        "تسليم منتجات",
        "محترف ثنائي اللغة",
      ],
    },
    work: {
      title: "الأعمال ودراسات الحالة",
      description: "مواقع ومنتجات رقمية مختارة مبنية على الوضوح والثقة وسهولة الاستخدام على الجوال ومسارات تواصل مباشرة.",
      image: "/images/projects/adtransporte-home.png",
      keywords: [
        "أعمال",
        "دراسات حالة",
        "معرض أعمال",
        "مشاريع",
        "مواقع",
        "مواقع شركات",
        "Schnell Sicher Umzug",
        "AD Fahrzeugtransporte",
        "MoPlayer",
        "تصميم يركّز على التحويل",
      ],
    },
    youtube: {
      title: "يوتيوب",
      description: "مراجعات وشروحات تقنية عربية وتجارب Android TV وقصص منتجات مع تواريخ النشر الحقيقية.",
      image: "/images/yt-channel-hero.png",
      keywords: [
        "يوتيوب تقني عربي",
        "مراجعات تقنية",
        "شروحات",
        "Android TV",
        "MoPlayer",
        "قناة تقنية",
        "محمد الفراس يوتيوب",
      ],
    },
    contact: {
      title: "تواصل",
      description: "ابدأ مشروع موقع أو صفحة منتج أو إعادة تصميم أو اطلب دعم MoPlayer مباشرة من محمد الفراس.",
      image: "/images/service_tech.png",
      keywords: [
        "تواصل مع محمد الفراس",
        "توظيف مطور ويب",
        "ابدأ مشروعاً",
        "طلب عرض سعر موقع",
        "استفسار تصميم موقع",
        "دعم MoPlayer",
      ],
    },
    privacy: {
      title: "الخصوصية",
      description: "كيفية تعامل moalfarras.space مع طلبات التواصل ورسائل الدعم وبيانات المنتجات والتنزيلات والخدمات المرتبطة.",
      image: "/images/logo.png",
      keywords: ["سياسة الخصوصية", "معالجة البيانات", "moalfarras.space", "حماية البيانات"],
    },
    apps: {
      title: "التطبيقات والمنتجات",
      description: "استكشف MoPlayer Classic وMoPlayer Pro وإصدارات الكمبيوتر والتفعيل والتنزيلات الرسمية والدعم والتحديثات.",
      image: "/images/moplayer-pro-hero.webp",
      keywords: [
        "MoPlayer",
        "MoPlayer Classic",
        "MoPlayer Pro",
        "MoPlayer PC",
        "مشغل IPTV",
        "مشغل Xtream",
        "مشغل M3U",
        "مشغل Android TV",
        "مشغل Fire TV",
        "مشغل ويندوز",
        "تفعيل التطبيق",
        "تنزيلات رسمية",
        "تطبيقات مشغل وسائط",
      ],
    },
  },
} satisfies Record<Locale, Record<string, SeoPage>>;
