import type { Locale } from "@/types/cms";

type SeoPage = {
  title: string;
  description: string;
  image: string;
  keywords?: string[];
};

export const seoData = {
  en: {
    home: {
      title: "Web, Apps & Digital Products",
      description: "Mohammad Alfarras builds bilingual websites, product interfaces, MoPlayer apps, and clear Arabic technology content from Germany.",
      image: "/images/protofeilnew.jpeg",
      keywords: [
        "Mohammad Alfarras",
        "web developer Germany",
        "Next.js developer",
        "React developer",
        "bilingual websites",
        "Arabic RTL websites",
        "MoPlayer",
        "IPTV player app",
        "Android TV apps",
        "product UI design",
        "landing pages",
        "digital products",
        "freelance web developer",
      ],
    },
    about: {
      title: "About",
      description: "Meet Mohammad Alfarras, a Germany-based builder working across web interfaces, digital products, logistics, and Arabic tech content.",
      image: "/images/protofeilnew.jpeg",
      keywords: [
        "Mohammad Alfarras",
        "about Mohammad Alfarras",
        "web developer",
        "product builder",
        "Germany",
        "Syria",
        "logistics",
        "Arabic tech content creator",
      ],
    },
    services: {
      title: "Web & Product Services",
      description: "Web design, Next.js development, bilingual RTL interfaces, product pages, UI/UX, and practical digital delivery.",
      image: "/images/service_web.png",
      keywords: [
        "web design",
        "web development",
        "Next.js development",
        "React",
        "RTL Arabic websites",
        "bilingual websites",
        "landing pages",
        "UI/UX design",
        "product pages",
        "SEO",
        "web performance",
        "web apps",
        "hire web developer",
      ],
    },
    cv: {
      title: "CV",
      description: "Professional experience across logistics operations, web engineering, product delivery, and bilingual communication.",
      image: "/images/portrait.jpg",
      keywords: [
        "Mohammad Alfarras CV",
        "resume",
        "web engineer",
        "frontend developer",
        "logistics operations",
        "product delivery",
        "bilingual professional",
      ],
    },
    work: {
      title: "Work & Case Studies",
      description: "Selected websites and product case studies shaped around clarity, trust, mobile usability, and direct conversion paths.",
      image: "/images/projects/adtransporte-home.png",
      keywords: [
        "portfolio",
        "case studies",
        "web design portfolio",
        "projects",
        "websites",
        "business websites",
        "Schnell Sicher Umzug",
        "AD Fahrzeugtransporte",
        "MoPlayer",
        "conversion-focused design",
      ],
    },
    youtube: {
      title: "YouTube",
      description: "Arabic technology reviews, practical tutorials, Android TV experiments, and product stories with real publication dates.",
      image: "/images/yt-channel-hero.png",
      keywords: [
        "Arabic tech YouTube",
        "technology reviews",
        "tutorials",
        "Android TV",
        "MoPlayer",
        "tech channel",
        "Mohammad Alfarras YouTube",
      ],
    },
    contact: {
      title: "Contact",
      description: "Start a website, product page, redesign, MoPlayer support, or digital presentation project with Mohammad Alfarras.",
      image: "/images/service_tech.png",
      keywords: [
        "contact Mohammad Alfarras",
        "hire web developer",
        "start a project",
        "website quote",
        "web design inquiry",
        "MoPlayer support",
      ],
    },
    privacy: {
      title: "Privacy",
      description: "How moalfarras.space handles contact requests, support messages, product data, downloads, and related services.",
      image: "/images/logo.png",
      keywords: ["privacy policy", "data handling", "moalfarras.space", "data protection"],
    },
    apps: {
      title: "Apps & Products",
      description: "Explore MoPlayer Classic, MoPlayer Pro, PC releases, activation, official downloads, support, and product updates.",
      image: "/images/moplayer-pro-hero.webp",
      keywords: [
        "MoPlayer",
        "MoPlayer Classic",
        "MoPlayer Pro",
        "MoPlayer PC",
        "IPTV player",
        "Xtream player",
        "M3U player",
        "Android TV player",
        "Fire TV player",
        "Windows media player",
        "app activation",
        "official downloads",
        "media player apps",
      ],
    },
  },
  ar: {
    home: {
      title: "ويب وتطبيقات ومنتجات رقمية",
      description: "يبني محمد الفراس مواقع ثنائية اللغة وواجهات منتجات وتطبيقات MoPlayer ومحتوى تقنياً عربياً واضحاً من ألمانيا.",
      image: "/images/protofeilnew.jpeg",
      keywords: [
        "محمد الفراس",
        "مطور ويب",
        "مطور Next.js",
        "تصميم مواقع",
        "مواقع عربية",
        "مواقع ثنائية اللغة",
        "MoPlayer",
        "تطبيق IPTV",
        "تطبيقات Android TV",
        "تصميم واجهات",
        "صفحات هبوط",
        "منتجات رقمية",
        "مطور ويب مستقل",
      ],
    },
    about: {
      title: "عن محمد الفراس",
      description: "تعرّف على محمد الفراس وخبرته في واجهات الويب والمنتجات الرقمية واللوجستيات وصناعة المحتوى التقني العربي.",
      image: "/images/protofeilnew.jpeg",
      keywords: [
        "محمد الفراس",
        "من هو محمد الفراس",
        "مطور ويب",
        "صانع منتجات رقمية",
        "ألمانيا",
        "سوريا",
        "لوجستيات",
        "محتوى تقني عربي",
      ],
    },
    services: {
      title: "خدمات الويب والمنتجات",
      description: "تصميم وتطوير مواقع Next.js وواجهات عربية وإنجليزية وRTL وصفحات منتجات وتجارب UI/UX عملية.",
      image: "/images/service_web.png",
      keywords: [
        "تصميم مواقع",
        "تطوير مواقع",
        "تطوير Next.js",
        "React",
        "مواقع عربية RTL",
        "مواقع ثنائية اللغة",
        "صفحات هبوط",
        "تصميم واجهات UI/UX",
        "صفحات منتجات",
        "تحسين محركات البحث SEO",
        "أداء المواقع",
        "تطبيقات ويب",
        "توظيف مطور ويب",
      ],
    },
    cv: {
      title: "السيرة الذاتية",
      description: "خبرة مهنية تجمع العمليات اللوجستية وهندسة الويب وتسليم المنتجات والتواصل بالعربية والألمانية والإنجليزية.",
      image: "/images/portrait.jpg",
      keywords: [
        "سيرة محمد الفراس الذاتية",
        "السيرة الذاتية",
        "مهندس ويب",
        "مطور واجهات",
        "عمليات لوجستية",
        "تسليم منتجات",
        "محترف ثنائي اللغة",
      ],
    },
    work: {
      title: "الأعمال ودراسات الحالة",
      description: "مواقع ومنتجات رقمية مختارة مبنية على الوضوح والثقة وسهولة الاستخدام على الجوال ومسارات تواصل مباشرة.",
      image: "/images/projects/adtransporte-home.png",
      keywords: [
        "أعمال",
        "دراسات حالة",
        "معرض أعمال",
        "مشاريع",
        "مواقع",
        "مواقع شركات",
        "Schnell Sicher Umzug",
        "AD Fahrzeugtransporte",
        "MoPlayer",
        "تصميم يركّز على التحويل",
      ],
    },
    youtube: {
      title: "يوتيوب",
      description: "مراجعات وشروحات تقنية عربية وتجارب Android TV وقصص منتجات مع تواريخ النشر الحقيقية.",
      image: "/images/yt-channel-hero.png",
      keywords: [
        "يوتيوب تقني عربي",
        "مراجعات تقنية",
        "شروحات",
        "Android TV",
        "MoPlayer",
        "قناة تقنية",
        "محمد الفراس يوتيوب",
      ],
    },
    contact: {
      title: "تواصل",
      description: "ابدأ مشروع موقع أو صفحة منتج أو إعادة تصميم أو اطلب دعم MoPlayer مباشرة من محمد الفراس.",
      image: "/images/service_tech.png",
      keywords: [
        "تواصل مع محمد الفراس",
        "توظيف مطور ويب",
        "ابدأ مشروعاً",
        "طلب عرض سعر موقع",
        "استفسار تصميم موقع",
        "دعم MoPlayer",
      ],
    },
    privacy: {
      title: "الخصوصية",
      description: "كيفية تعامل moalfarras.space مع طلبات التواصل ورسائل الدعم وبيانات المنتجات والتنزيلات والخدمات المرتبطة.",
      image: "/images/logo.png",
      keywords: ["سياسة الخصوصية", "معالجة البيانات", "moalfarras.space", "حماية البيانات"],
    },
    apps: {
      title: "التطبيقات والمنتجات",
      description: "استكشف MoPlayer Classic وMoPlayer Pro وإصدارات الكمبيوتر والتفعيل والتنزيلات الرسمية والدعم والتحديثات.",
      image: "/images/moplayer-pro-hero.webp",
      keywords: [
        "MoPlayer",
        "MoPlayer Classic",
        "MoPlayer Pro",
        "MoPlayer PC",
        "مشغل IPTV",
        "مشغل Xtream",
        "مشغل M3U",
        "مشغل Android TV",
        "مشغل Fire TV",
        "مشغل ويندوز",
        "تفعيل التطبيق",
        "تنزيلات رسمية",
        "تطبيقات مشغل وسائط",
      ],
    },
  },
} satisfies Record<Locale, Record<string, SeoPage>>;
